UnicornLog/UnicornLog/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('UnicornLog_REST.urls')),
    path('users/', include('users.urls')),
]

UnicornLog/UnicornLog_REST/api/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from UnicornLog_REST import views #TODO: need views for the API.

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

UnicornLog/UnicornLog_REST/urls.py
"""defines url patters for UnicornLog_REST"""
from django.urls import path
from . import views

app_name = 'UnicornLog_REST'
urlpatterns = [
    #home page
    path('', views.index, name= 'index'),
    path('index/', views.index, name = 'index'),
    path('Index/', views.index, name = 'index'),
   
    #Unicorns page
    path('unicorns/', views.unicorns, name = 'unicorns'),
    path('Unicorns/', views.unicorns, name = 'unicorns'),
    #path('unicorns/<int:unicorn_id>', views.Unicorns, name= 'Unicorns'),
    #Sightings page
    path('Sightings/', views.sightings, name = 'sightings'),
    path('sightings/', views.sightings, name = 'sightings'),
    #path('sightings/<int:sighting_id>', views.Sightings, name= 'Sightings'),
    #Locations page
    path('Locations/', views.locations, name='locations'),
    path('locations/', views.locations, name = 'locations'),
    path('new_location/', views.new_location, name='new_location'),
    
    #view location_id
    path('location/<int:location_id>', views.location, name= 'location'),
    path('Location/<int:location_id>', views.location, name= 'location'),
    
    #overview page
]

UnicornLog/users/urls.py
'''defines url patters for the users app'''

from django.urls import path, include
from . import views
app_name= 'users'
urlpatterns = [
    #default auth urls
    path('', include('django.contrib.auth.urls')),
    #regitration page
    path('register/', views.register, name='register'),
]

UnicornLog/UnicornLog_REST/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
#from django_countries.fields import CountryField

#--- perhaps go with other API features
#from pygments.lexers import get_all_lexers
#from pygments.styles import get_all_styles
#LEXERS = [item for item in get_all_lexers() if item[1]]
#LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
#STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


# Create your models here.


class Location(models.Model):
    """the location of a sighting"""
    name = models.CharField(max_length=255)
#    country = CountryField()
    class Meta:
        verbose_name_plural = 'Locations'
        
    def __str__(self):
        """returns thy self as text"""
        return self.name    

class Unicorn(models.Model):
    """this is a Unicorn"""
    name = models.CharField(max_length=255)
    class Color(models.TextChoices):
        white = "White"
        gray = "Gray"
        black = "black"
        Sparkle= "Sparkle"
        rainbow = "Rainbow"
    color = Color.choices
    RainbowPoop = models.BooleanField(default=False)
    description = models.TextField()
    class Meta:
        verbose_name_plural = 'Unicorns'
        
    def __str__(self):
        """returns thy self as text"""
        return self.name

class Sighting(models.Model):
    """an individual sighting of a unicorn"""
    location = models.ForeignKey(Location, on_delete=CASCADE)
    description = models.TextField()
    unicorn = models.ForeignKey(Unicorn, on_delete=CASCADE)
    date = models.DateField(("Month, day, Year"), auto_now=False, auto_now_add=False)
    witness = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = 'Sightings'
        
    class TimeOfDay(models.TextChoices):
        morning = 'Morning'
        afternoon = 'Afternoon'
        evening = 'Evening'
        night = 'Night'
        
    def __str__(self):
        """returns thy self as text"""
        return self.description

UnicornLog/UnicornLog_REST/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import *
#TODO: add 'create' functions for sightings & unicorns

class locationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['name']
        label ={'name': ''}

class sightingsForm(forms.ModelForm):
    class Meta:
        model = Sighting
        #need to add the unicorn and the location
        fields = ['description', 'date']
        label = {'description' : Sighting.description, 'date' : ''}

class unicornsForm(forms.ModelForm):
    class Meta:
        pass
        #model = Unicorn
        #fields = ['name', 'color', 'description']
        #label = {'name': Unicorn.name, 'description' : Unicorn.description}
        #widgets = {''}

UnicornLog/UnicornLog_REST/api/views.py
from django.db import models
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import UserSerializer, GroupSerializer

# ViewSets for REST api
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

UnicornLog/UnicornLog_REST/views.py
#from django.db import models
from django.http.response import Http404
from django.shortcuts import redirect, render
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from .models import Location, Unicorn, Sighting
from .forms import *

#TODO: add new/edit views & forms for Sightings & Unicorn types

#views 
def index(request):
    """home page for UnicornLog_REST"""
    return render(request, 'std/index.html')

#TODO does not print the location name, needs fix
def locations(request):
    """view the locations page"""
    locations = Location.objects.all()
    context = {'locations': locations}
    return render(request, 'std/Locations.html', context)

def location(request, location_id):
    location = Location.objects.get(id=location_id)
    context = {'Location': location.name}
    return render(request, 'std/Location.html', context)

@login_required
def new_location(request):
    '''add a new location'''
    if request.method != 'POST':
        form = locationForm()
    else:
        #POST data is submitted, time to process
        form = locationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('UnicornLog_REST:locations')
    context = {'form': form}
    return render(request, 'std/new_location.html', context)
        
def unicorns(request):
    """view the Unicorns page"""
    unicorns = Unicorn.objects.all()
    context = {'Unicorns': unicorns}
    return render(request, 'std/Unicorns.html', context)

def unicorn(request, Unicorn_id):
    unicorn = Unicorn.objects.get(id=Unicorn_id)
    #add sightings foriegn Key
    #sightingsList = Sightings.objects.get(Unicorn_id)
    context = {'Unicorn': unicorn}
    return render(request, 'std/Unicorn.html', context)    

@login_required
def new_unicorn(request):
    pass

@login_required
def edit_unicorn(request):
    pass
    
def sightings(request):
    """view the sightings page"""
    sightings = Sighting.objects.all()
    context = {'sightings': sightings}
    return render(request, 'std/Sightings.html', context)

def sighting(request, sighting_id):
    pass

@login_required
def new_sighting(request):
    '''adds a new sighting'''
    if(request.method != 'POST'):
        #form= SightingForm()
        pass
    else:
        form = None
        #form = SightingForm(data=request.POST)
        if form.is_valid():
            new_sighting =form.save(commit = False)
            new_sighting.witness = request.user
            new_sighting.save()
            return redirect('UnicornLog_REST:index')
    context = {'form': form}
    return render(request, 'std/new_sighting.html', context)

@login_required
def edit_sighting(request, sighting_id):
    '''shows a single sighting'''
    sighting = Sighting.objects.get(id = sighting_id)
    if sighting.witness != request.user:
        raise Http404
    
    pass

    
    

UnicornLog/UnicornLog_REST/templates/std/Location.html
{% extends 'std/base.html' %}

{%block content%}

<p> Location: {{ location }} </p> 

{%endblock content%}

UnicornLog/UnicornLog_REST/templates/std/Locations.html
{% extends 'std/base.html' %}

{%block content%}

<p> Locations </p> 

<ul>
    {% for location in locations%}
        <li> <a href={% url 'UnicornLog_REST:location' location.id %}> {{location}} </li>
        {% empty %}
        <li> no locations in db </li>
     {% endfor %}
</ul>

<a href="{% url 'UnicornLog_REST:new_location' %}"> Add a location </a>

{%endblock content%}

UnicornLog/UnicornLog_REST/templates/std/Sightings.html
{% extends 'std/base.html' %}

{%block content%}

<p> Show me the sightings</p>
 <ul>
    {% for Sighting in Sightings%}
        <li> {{Sightings}}</li>
        {% empty %}
        <li> no sightings in db </li>
     {% endfor %}
</ul>

{%endblock content%}

UnicornLog/UnicornLog_REST/templates/std/Unicorn.html
{% extends 'std/base.html' %}

{%block content%}

<p> Unicorn: {{Unicorn}} </p> 

{%endblock content%}

UnicornLog/UnicornLog_REST/templates/std/Unicorns.html
{% extends 'std/base.html' %}

{%block content%}

<p> Show me the Unicorns!!!!!</p>
<ul>
    {% for Unicorn in Unicorns%}
        <li> {{Unicorn}}</li>
        {% empty %}
        <li> no Unicorns in db </li>
     {% endfor %}
</ul>

{%endblock content%}

UnicornLog/UnicornLog_REST/templates/std/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang='en'>
<head>
    <meta charset="utf-8">
    <meta name = 'viewport' content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title> Unicorn Logs!</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class='navbar navbar-expand-md navbar-light bg-light mb-4 border'>
        <a class='navbar-brand' href="{% url 'UnicornLog_REST:index' %}"> Unicorn Log </a>

        <button class='navbar-toggler' type="button" 
            data-toggle="collapse" data-target="#navbarCollapse" 
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>
        </button>
        <div class='collapse navbar-collapse' id='navbarCollapse'>
            <ul class ='navbar-nav mr-auto'>
                <li class='nav-items'>
                    <a class="nav-link" href="{% url 'UnicornLog_REST:unicorns' %}"> Unicorns </a>
                </li>
                <li class='nav-items'>
                    <a class="nav-link" href="{% url 'UnicornLog_REST:locations' %}"> Locations </a>
                </li>
                <li class='nav-items'>
                    <a class="nav-link" href="{% url 'UnicornLog_REST:sightings' %}"> Sightings </a>
                </li>
            </ul>
            <ul class='navbar-nav ml-auto'>
                {%if user.is_autheticated %}
                    <li class='nav-item'>
                        <span class='navbar-text'>Hi, {{ user.username }}.</span>
                    </li>
                    <li class='nav-item'>
                        <a class 'nav-link' href="{% url 'users:logout' %}">Log out</a>
                    </li>
                    {% else %}
                    <li class='nav-item'>
                        <a class 'nav-link' href="{% url 'users:login' %}">Log in</a>
                    </li>
                    <li class='nav-item'>
                        <a class 'nav-link' href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif%}
            </ul>
        </div>
    </nav>
    <main role="main" class="containers">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %} 
            {% endblock page_header %}
        </div>
        <div>
            {% block content %} 
            {% endblock content %}
        </div>
    </main>
</body>
</html>

UnicornLog/UnicornLog_REST/templates/std/index.html
{% extends 'std/base.html' %}

{%block page_header%}
    <div class='jumbotron'>
        <h1 class="display-3"> Let's Find the Unicorns. </h1>
        <p class='lead'> this sight is to record the sightings of unicorns, thier locations,
         the color of the unicorn and if the unicon pooped a rainbow </p>

        <a class='btn btn-lg btn-primary' href="{% url 'users:register' %}"
            role='button'> Register &raquo; </a>
    </div>

{%endblock page_header%}

UnicornLog/UnicornLog_REST/templates/std/new_location.html
{% extends 'std/base.html' %}
{%block content%}

<p> New Location! </p> 

<form action="{% url 'UnicornLog_REST:new_location' %}" method = 'post'>
    {% csrf_token %} <!-- this is a type of securty token-->
    {{form.as_p}}
    <button name="submit">Add Location</button>
</form>

{%endblock content%}